### ISSUE TITLE
`UnsupportedFeatureException: An object of type 'org.apache.pdfbox.rendering.ImageType$2' was found in the image heap`

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-tika#168]
Native image build fails with 
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'org.apache.pdfbox.rendering.ImageType$2' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
```

More info: https://github.com/quarkiverse/quarkus-tika/actions/runs/6794028039/job/18469822743

**Comment by gastaldi** [comment]
@melloware any idea what could be causing this?

**Comment by melloware** [comment]
No I looked it started with a recent graalvm change. It's like it can't find that inner class?

**Comment by melloware** [comment]
It is a funky class: https://github.com/apache/pdfbox/blob/trunk/pdfbox/src/main/java/org/apache/pdfbox/rendering/ImageType.java

I wonder if its missing the `import java.awt.image.BufferedImage;` or something it doesn't like about this enum?

**Comment by melloware** [comment]
Looks like this didn't fix it.

**Comment by melloware** [comment]
Interesting its $1 now and not $2  `org.apache.pdfbox.rendering.ImageType$1` ?

**Comment by gastaldi** [comment]
> Interesting its $1 now and not $2 `org.apache.pdfbox.rendering.ImageType$1` ?

I was about to comment that now 😛 

@zakkak is this a GraalVM issue?

**Comment by zakkak** [comment]
@gastaldi I don't think so.

Without looking more into the issue my understanding is that these synthetic classes are marked as runtime initialized due to:

``` RuntimeClassInitialization.initializeAtRunTime("org.apache.pdfbox.rendering", reason)
```

but some other class that is build time initialized creates and stores an instance of them in the image heap.

Running with `--trace-object-instantiation=org.apache.pdfbox.rendering.ImageType$2` should give you the name of this class, which you can then mark as runtime initialized to resolve the issue.

@Karm might have some more info to share

**Comment by melloware** [comment]
Trying this now @zakkak thanks for the hint.

**Comment by melloware** [comment]
```
The culprit object has been instantiated by the 'io.quarkus.runner.ApplicationImpl' class initializer with the following trace:
	at org.apache.pdfbox.rendering.ImageType$2.<init>(ImageType.java:37)
	at org.apache.pdfbox.rendering.ImageType.<clinit>(ImageType.java:37)
	at org.apache.tika.parser.pdf.PDFParserConfig.<init>(PDFParserConfig.java:117)
	at org.apache.tika.parser.pdf.PDFParser.<init>(PDFParser.java:139)
	at java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(DirectMethodHandle$Holder)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at jdk.internal.reflect.DirectConstructorHandleAccessor.invokeImpl(DirectConstructorHandleAccessor.java:86)
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
	at java.lang.Class.newInstance(Class.java:725)
	at org.apache.tika.config.TikaConfig$ParserXmlLoader.newInstance(TikaConfig.java:1022)
	at org.apache.tika.config.TikaConfig$ParserXmlLoader.newInstance(TikaConfig.java:866)
	at org.apache.tika.config.TikaConfig$XmlLoader.loadOne(TikaConfig.java:791)
	at org.apache.tika.config.TikaConfig$XmlLoader.loadOverall(TikaConfig.java:681)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:176)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:156)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:148)
	at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:144)
	at io.quarkus.tika.runtime.TikaRecorder.initializeParser(TikaRecorder.java:30)
	at io.quarkus.tika.runtime.TikaRecorder.initTikaParser(TikaRecorder.java:21)
	at io.quarkus.deployment.steps.TikaProcessor$initializeTikaParser1762155120.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.TikaProcessor$initializeTikaParser1762155120.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
```

**Comment by zakkak** [comment]
@melloware @gastaldi I opened a PR that seems to resolve the issue, please review https://github.com/quarkiverse/quarkus-tika/pull/172
