### ISSUE TITLE
Dependency issue on Quarkus 3.5.x

### ISSUE THREAD

**Issue by b-thiswatch** [quarkiverse/quarkus-tika#176]
Hi there,

I have added the Apache Tika extension to my Quarkus project. Also I am using optimaize and tika-serialization.

```kotlin
dependencies {
    implementation("io.quarkiverse.tika:quarkus-tika:2.0.3")
...
    implementation("org.apache.tika:tika-langdetect-optimaize:2.8.0")
    implementation("org.apache.tika:tika-serialization:2.8.0")
```

Please note first that I used 2.8.0, because (although package should use 2.9.1) the extension uses tika 2.8.0. When upgrading to Quarkus 3.5.x the following code does not run anymore

```kotlin
fun parseFile(file: File): FileParserResult {

        val config = TesseractOCRConfig()
        config.isSkipOcr = true
        val context = ParseContext()
        context.set(TesseractOCRConfig::class.java, config)

        val stream = FileInputStream(file)
        val parser = AutoDetectParser()
        val handler = BodyContentHandler(-1)
        val metadata = Metadata()

        parser.parse(stream, handler, metadata, context)
...
```

It fails with

```shell
Test FileParserTest#Reading content from pdf file works() failed 
: java.lang.NoSuchMethodError: 'org.apache.fontbox.ttf.TrueTypeFont org.apache.fontbox.ttf.TTFParser.parse(java.io.InputStream)'
        at org.apache.pdfbox.pdmodel.font.FontMapperImpl.<init>(FontMapperImpl.java:130)
        at org.apache.pdfbox.pdmodel.font.FontMappers$DefaultFontMapper.<clinit>(FontMappers.java:36)
        at org.apache.pdfbox.pdmodel.font.FontMappers.instance(FontMappers.java:46)
        at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:217)
        at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:89)
        at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:171)
        at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:66)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:966)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:541)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:516)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:155)
        at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:155)
        at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:363)
        at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:137)
        at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1370)
        at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:238)
        at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:108)
        at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:212)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:199)
        at com.thiswatch.watch.backend.baryl.domain.model.fileparser.FileParser.parseFile(FileParser.kt:29)

```

Thanks for any advice.

**Comment by b-thiswatch** [comment]
@melloware thanks for checking this out

That is what I meant with "(although package should use 2.9.1) ". I have seen in the pom.xml that it uses 2.9.1 but for me it pulls 2.8.0 no matter how often I clean and reimport the project.

Anyway, using 2.9.1 on my dependencies is not the solution. It works fine with Quarkus 3.4.3, but with >= 3.5.0 it does not work anymore.

**Comment by melloware** [comment]
@b-thiswatch I would like to investigate this but I see you posted Kotlin code.  I will add an integration Test but I would prefer it was Java code and can you explain what your code is doing?  I have never heard of TesseractOCR before 😄

**Comment by b-thiswatch** [comment]
@melloware 

I can try and assemble a simple reproducer with java. It will take me a moment, though.

Tesseract is an OCR Tool and TesseractOCRConfig() is in the org.apache.tika.parser.ocr.TesseractOCRConfig package.
https://github.com/tesseract-ocr/tesseract


What the code basically does is to parse a file (MS Office, plain text, email, PDF), get the content (either embedded or if an image or PDF without text via OCR), detect the language to put it in the correct OpenSearch index later....

**Comment by melloware** [comment]
Awesome if you can put together a little sample I can create a test and then we can figure out what is going on!

**Comment by b-thiswatch** [comment]
@melloware long story short: it does not seem to be related to this extension. 

Long version:
While building the reproducer, I realised it is working just fine. What amazes me, is that the reproducer project downloads 2.9.1 no problem. 
My real project still downloads 2.8.0. I deleted every gradle cache, invalidated all Intellij caches - still no look.

The craziest part is below. When running gradles dependencyInsight on 2.0.3 it even tells me it uses 2.0.2. 

I'm stuck ¯\_(ツ)_/¯

```shell
./gradlew dependencyInsight --dependency io.quarkiverse.tika:quarkus-tika:2.0.3

Welcome to Gradle 8.4!

Here are the highlights of this release:
 - Compiling and testing with Java 21
 - Faster Java compilation on Windows
 - Role focused dependency configurations creation

For more details see https://docs.gradle.org/8.4/release-notes.html

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :dependencyInsight
io.quarkiverse.tika:quarkus-tika:2.0.2

```

**Comment by melloware** [comment]
Should I close the ticket and we can blame Gradle?

**Comment by b-thiswatch** [comment]
I think it's due to me also using the Quarkus Camel Extension.

As soon as I add 

implementation(enforcedPlatform("${quarkusPlatformGroupId}:quarkus-camel-bom:${quarkusPlatformVersion}"))

io.quarkiverse.tika:quarkus-tika:2.0.2 will be used.
This is interesting, because I am not using camel-quarkus-tika, but adding just the camel-bom is enough

**Comment by melloware** [comment]
Yep I would open at Camel.
