### ISSUE TITLE
Quarkus Tika Native Image Build Error

### ISSUE THREAD

**Issue by mustafacalik** [quarkiverse/quarkus-tika#51]
When I tried Quarkus Tika with "https://code.quarkus.io/d?e=awt&e=io.quarkiverse.tika%3Aquarkus-tika&cn=code.quarkus.io", i didn't get any error while building as native image.

But when I added a code block to use Tika parser and not typing any parser, it gave the following error.

> quarkus.tika.parsers=pdf

`Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime. To see how this object got instantiated use --trace-object-instantiation=org.apache.sis.internal.system.DelayedExecutor.
`

To reproduce it add the folowing dependency and code block.

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
```

```
@Path("/parse")
public class TikaParserResource {
    private static final Logger log = Logger.getLogger(TikaParserResource.class);

    @Inject
    TikaParser parser;

    @POST
    @Path("/text")
    @Produces(MediaType.TEXT_PLAIN)
    public String extractText(InputStream stream) {
        Instant start = Instant.now();
        String text = "empty";
        try {
            text = parser.getText(stream);
        } catch (Exception e) {
            log.info("error" + e);
            text = "error";
        }
        Instant finish = Instant.now();
        log.info(Duration.between(start, finish).toMillis() + " mls have passed");
        return text;
    }
}
```

As a solution, i gave the package as initilize-at-run-time parameter but after that it continued to give error

> quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.sis.internal.system\,ucar.nc2.grib.grib2

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: ucar.nc2.grib.grib2.Grib2JpegDecoder.<init>(int, boolean). This error is reported at image build time because class ucar.nc2.grib.grib2.Grib2DataReader2 is registered for linking at image build time by command line
Detailed message:
Trace: 
        at parsing ucar.nc2.grib.grib2.Grib2DataReader2.getData40(Grib2DataReader2.java:727)
Call path from entry point to ucar.nc2.grib.grib2.Grib2DataReader2.getData40(RandomAccessFile, Grib2Drs$Type40): 
        at ucar.nc2.grib.grib2.Grib2DataReader2.getData40(Grib2DataReader2.java:716)
        at ucar.nc2.grib.grib2.Grib2DataReader2.getData(Grib2DataReader2.java:109)
        at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:321)
        at ucar.nc2.grib.collection.Grib2Iosp.readData(Grib2Iosp.java:405)
        at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:940)
        at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:860)
        at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:810)
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1986)
        at ucar.nc2.Variable.reallyRead(Variable.java:860)
        at ucar.nc2.Variable._read(Variable.java:831)
        at ucar.nc2.Variable.read(Variable.java:709)
        at ucar.nc2.NCdumpW.printVariableData(NCdumpW.java:386)
        at ucar.nc2.dt.grid.GridCoordSys.showCoords(GridCoordSys.java:1405)
        at ucar.nc2.dt.grid.GridCoordSys.show(GridCoordSys.java:1355)
        at ucar.nc2.dt.grid.GridCoordSys.toString(GridCoordSys.java:1345)
        at sun.java2d.loops.GraphicsPrimitive.simplename(GraphicsPrimitive.java:599)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_GraphicsPrimitive_simplename_202a3eedb200439fc8661f318bfce7d323ea7603(generated:0)
```

**Comment by gastaldi** [comment]
I performed the same steps and I failed to reproduce the problem. I am closing it since it seems to be stale. Please reopen and attach a reproducer if the problem persists.
