### ISSUE TITLE
Quarkus Tika Native Config Path Not Works

### ISSUE THREAD

**Issue by mustafacalik** [quarkiverse/quarkus-tika#52]
I put tika-config.xml with the following content and its reference in application.properties. When i build the project as native, i got the following error.

### tika-config.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<properties>
    <parsers>
        <parser class="org.apache.tika.parser.DefaultParser">
            <mime-exclude>application/pdf</mime-exclude>
<!--            <mime>text/plain</mime>-->
        </parser>
    </parsers>
</properties>
```

### application.properties

```
quarkus.native.additional-build-args =-H:ResourceConfigurationFiles=resources-config.json
quarkus.tika.tika-config-path=tika-config.xml
```

### resources-config.json

```
{
  "resources": [
    {
      "pattern": ".*\\.xml$"
    }
  ]
}
```

```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=org.apache.sis.internal.system.DelayedExecutor. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
        at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by melloware** [comment]
@mustafacalik Is this the same issue as the other one?  It looks identical Error?

**Comment by melloware** [comment]
Never heard back from OP.
